/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  type Handlers = {
    'ReceiveWebhook': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'PullCode': EventHandler<never, never>
    'DeployApp': EventHandler<never, never>
  }
}